# .travis.yml

language: php
dist: bionic
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial

# Install dependencies before testing
before_script:
  - composer selfupdate
  - composer install --dev

# Use our custom version of phpunit
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

# Run coveralls.io code coverage report
after_script:
  - vendor/bin/php-coveralls -v
